title: Chat²GPT 🤖💬
description: Chat²GPT is a ChatGPT chat bot for Google Chat. 🤖💬
theme: just-the-docs

url: https://rahb-realtors-association.github.io/chat2gpt/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
