name: GCP Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: $GCP_PROJECT_ID
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - run: gcloud functions deploy chat2gpt --runtime python39 --trigger-http --allow-unauthenticated --entry-point process_event --region $GCP_REGION --set-env-vars OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }},MODEL_NAME=$MODEL_NAME,SYSTEM_PROMPT=$SYSTEM_PROMPT
